clc;


EXPECTED_PACKET_SIZE = 61;

numSteps = length(Time);


requiredVariables = { ...
    'Time', ...
    'Vehicle_ID', ...
    'Position', ...
    'Velocity', ...
    'Segment_Status' ...
};

for variableIndex = 1:length(requiredVariables)

    variableName = requiredVariables{variableIndex};

    if ~exist(variableName, 'var')

        error( ...
            'Module2:MissingInput', ...
            ['Required Module 1 variable "%s" was not found. ' ...
             'Run module1_kinematics.m first.'], ...
            variableName ...
        );

    end

end

packetBufferHistory = zeros( ...
    numSteps, ...
    EXPECTED_PACKET_SIZE, ...
    'uint8' ...
);


serializedPacketCount = 0;


for k = 1:numSteps


    serializedTimestamp = double(Time(k));



    serializedVehicleID = uint32(Vehicle_ID(k));


    serializedPositionX = double(Position(k, 1));
    serializedPositionY = double(Position(k, 2));
    serializedPositionZ = double(Position(k, 3));


    serializedVelocityX = double(Velocity(k, 1));
    serializedVelocityY = double(Velocity(k, 2));
    serializedVelocityZ = double(Velocity(k, 3));


    serializedStatus = uint8(Segment_Status(k));


    timestampBytes = typecast( ...
        serializedTimestamp, ...
        'uint8' ...
    );

    vehicleIDBytes = typecast( ...
        serializedVehicleID, ...
        'uint8' ...
    );

    positionXBytes = typecast( ...
        serializedPositionX, ...
        'uint8' ...
    );

    positionYBytes = typecast( ...
        serializedPositionY, ...
        'uint8' ...
    );

    positionZBytes = typecast( ...
        serializedPositionZ, ...
        'uint8' ...
    );

    velocityXBytes = typecast( ...
        serializedVelocityX, ...
        'uint8' ...
    );

    velocityYBytes = typecast( ...
        serializedVelocityY, ...
        'uint8' ...
    );

    velocityZBytes = typecast( ...
        serializedVelocityZ, ...
        'uint8' ...
    );

    statusBytes = typecast( ...
        serializedStatus, ...
        'uint8' ...
    );


    packetBuffer = [ ...
        timestampBytes, ...
        vehicleIDBytes, ...
        positionXBytes, ...
        positionYBytes, ...
        positionZBytes, ...
        velocityXBytes, ...
        velocityYBytes, ...
        velocityZBytes, ...
        statusBytes ...
    ];


    if length(packetBuffer) ~= EXPECTED_PACKET_SIZE

        error( ...
            'Module2:InvalidPacketSize', ...
            ['Serialization error at frame %d ' ...
             '(t = %.3f s). Expected exactly %d bytes, ' ...
             'but generated %d bytes.'], ...
            k, ...
            Time(k), ...
            EXPECTED_PACKET_SIZE, ...
            length(packetBuffer) ...
        );

    end


    packetBufferHistory(k, :) = packetBuffer;

    serializedPacketCount = serializedPacketCount + 1;

end


fprintf('\n');
fprintf('====================================================\n');
fprintf('MODULE 2 - BINARY TELEMETRY SERIALIZATION\n');
fprintf('====================================================\n');

fprintf( ...
    'Expected packet size       : %d bytes\n', ...
    EXPECTED_PACKET_SIZE ...
);

fprintf( ...
    'Simulation frames          : %d\n', ...
    numSteps ...
);

fprintf( ...
    'Packets successfully built : %d\n', ...
    serializedPacketCount ...
);


if serializedPacketCount ~= numSteps

    error( ...
        'Module2:PacketCountMismatch', ...
        ['Serialization failure: expected %d packets, ' ...
         'but generated %d packets.'], ...
        numSteps, ...
        serializedPacketCount ...
    );

end


fprintf( ...
    'Packet size verification   : PASSED\n' ...
);

fprintf( ...
    'Serialization status       : MODULE 2 PASSED\n' ...
);

fprintf('====================================================\n');


fprintf('\nFirst serialized packet:\n');

disp(packetBufferHistory(1, :));


fprintf( ...
    'First packet length: %d bytes\n', ...
    length(packetBufferHistory(1, :)) ...
);